const SET_TASKS = 'SET_TASKS';
const REPEATED_TASK = 'REPEATED_TASK';
const SET_POGRESS = 'SET_POGRESS';
const DELETE_TASK = 'DELETE_TASK';
const SET_MESSAGE = 'SET_MESSAGE'

export {
    SET_TASKS,
    SET_POGRESS,
    DELETE_TASK,
    REPEATED_TASK,
    SET_MESSAGE,
};
