const SET_TASKS = 'SET_TASKS';
const REPEATED_TASK = 'REPEATED_TASK';
const SET_POGRESS = 'SET_POGRESS';
const DELETE_TASK = 'DELETE_TASK';
const SET_MESSAGE = 'SET_MESSAGE';
const UPDATE_TASK = 'UPDATE_TASK';
const TOGGLE_NAVIGATION_ITEMS = 'TOGGLE_NAVIGATION_ITEMS';

export {
    SET_TASKS,
    SET_POGRESS,
    DELETE_TASK,
    REPEATED_TASK,
    SET_MESSAGE,
    UPDATE_TASK,
    TOGGLE_NAVIGATION_ITEMS,
};
